{% set name = "pz-rail-sklearn" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pz_rail_sklearn-{{ version }}.tar.gz
  sha256: 56ef4bf7353c58b352af8889217c1a6ea30b9f83a6a82858771a52014ade7380

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - pz-rail-base >=1.0.3
    - scikit-learn
    - pandas
test:
  imports:
    - rail.sklearn
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/LSSTDESC/rail_sklearn
  summary: RAIL estimators using scikit-learn regressors
  description: |
    RAIL is a flexible software library providing tools to produce at-scale photometric redshift data products, including uncertainties and summary statistics, and stress-test them under realistically complex systematics. 

extra:
  recipe-maintainers:
    - sschmidt23
    - eacharles
