{% set name = "pz-rail-sklearn" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pz_rail_sklearn-{{ version }}.tar.gz
  sha256: 34d2a07ccdb131fef0842d2999f8114febd01c97d32cca0d93b2d0e9653a9a4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - pz-rail-base >=1.0.3
    - scikit-learn
    - pandas
test:
  imports:
    - rail.sklearn
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/LSSTDESC/rail_sklearn
  summary: RAIL estimators using scikit-learn regressors
  description: |
    RAIL is a flexible software library providing tools to produce at-scale photometric redshift data products, including uncertainties and summary statistics, and stress-test them under realistically complex systematics. 

extra:
  recipe-maintainers:
    - sschmidt23
    - eacharles
